pb_teleop_twist_joy:
  ros__parameters:
    use_sim_time: false
    robot_base_frame: gimbal_yaw
    control_mode: manual_control  # Option: auto_control, manual_control

    require_enable_button: true
    enable_button: 7              # L1 shoulder button 使能移动：右肩键
    enable_turbo_button: 6        # R1 shoulder button 使能加速：左肩键

    axis_chassis:
      x: 1                        # Left thumb stick vertical  前后平移：左摇杆垂直
      y: 0                        # Left thumb stick horizontal 左右平移：左摇杆水平
      yaw: 6                      # button_left and button_right 旋转：右方向键
    scale_chassis:
      x: 2.5
      y: 2.5
      yaw: 3.0
    scale_chassis_turbo:
      x: 4.0
      y: 4.0
      yaw: 6.0

    axis_gimbal:
      roll: -1                    # Disable
      pitch: 3                    # Right thumb stick vertical 云台俯仰：右摇杆垂直
      yaw: 2                      # Right thumb stick horizontal 云台旋转：右摇杆水平
      shoot: 7                     # 开火：下方向键
    scale_gimbal:
      roll: 0.0
      pitch: -1.0
      yaw: 2.5
      shoot: 1.0
    scale_gimbal_turbo:
      roll: 0.0
      pitch: -1.5
      yaw: 3.5
      shoot: 1.0